# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ticket_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ticket_service.proto',
  package='tickets',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ticket_service.proto\x12\x07tickets\"O\n\x06Ticket\x12\x11\n\tticket_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\x05\x12\r\n\x05stake\x18\x03 \x01(\x01\x12\x0e\n\x06payout\x18\x04 \x01(\x01\"%\n\x10GetTicketRequest\x12\x11\n\tticket_id\x18\x01 \x01(\x05\"0\n\x19GetCustomerTicketsRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x32\x95\x01\n\rTicketService\x12\x37\n\tGetTicket\x12\x19.tickets.GetTicketRequest\x1a\x0f.tickets.Ticket\x12K\n\x12GetCustomerTickets\x12\".tickets.GetCustomerTicketsRequest\x1a\x0f.tickets.Ticket0\x01\x62\x06proto3'
)




_TICKET = _descriptor.Descriptor(
  name='Ticket',
  full_name='tickets.Ticket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='tickets.Ticket.ticket_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='tickets.Ticket.customer_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stake', full_name='tickets.Ticket.stake', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payout', full_name='tickets.Ticket.payout', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=112,
)


_GETTICKETREQUEST = _descriptor.Descriptor(
  name='GetTicketRequest',
  full_name='tickets.GetTicketRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket_id', full_name='tickets.GetTicketRequest.ticket_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=151,
)


_GETCUSTOMERTICKETSREQUEST = _descriptor.Descriptor(
  name='GetCustomerTicketsRequest',
  full_name='tickets.GetCustomerTicketsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='customer_id', full_name='tickets.GetCustomerTicketsRequest.customer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['Ticket'] = _TICKET
DESCRIPTOR.message_types_by_name['GetTicketRequest'] = _GETTICKETREQUEST
DESCRIPTOR.message_types_by_name['GetCustomerTicketsRequest'] = _GETCUSTOMERTICKETSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ticket = _reflection.GeneratedProtocolMessageType('Ticket', (_message.Message,), {
  'DESCRIPTOR' : _TICKET,
  '__module__' : 'ticket_service_pb2'
  # @@protoc_insertion_point(class_scope:tickets.Ticket)
  })
_sym_db.RegisterMessage(Ticket)

GetTicketRequest = _reflection.GeneratedProtocolMessageType('GetTicketRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTICKETREQUEST,
  '__module__' : 'ticket_service_pb2'
  # @@protoc_insertion_point(class_scope:tickets.GetTicketRequest)
  })
_sym_db.RegisterMessage(GetTicketRequest)

GetCustomerTicketsRequest = _reflection.GeneratedProtocolMessageType('GetCustomerTicketsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCUSTOMERTICKETSREQUEST,
  '__module__' : 'ticket_service_pb2'
  # @@protoc_insertion_point(class_scope:tickets.GetCustomerTicketsRequest)
  })
_sym_db.RegisterMessage(GetCustomerTicketsRequest)



_TICKETSERVICE = _descriptor.ServiceDescriptor(
  name='TicketService',
  full_name='tickets.TicketService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=204,
  serialized_end=353,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTicket',
    full_name='tickets.TicketService.GetTicket',
    index=0,
    containing_service=None,
    input_type=_GETTICKETREQUEST,
    output_type=_TICKET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCustomerTickets',
    full_name='tickets.TicketService.GetCustomerTickets',
    index=1,
    containing_service=None,
    input_type=_GETCUSTOMERTICKETSREQUEST,
    output_type=_TICKET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TICKETSERVICE)

DESCRIPTOR.services_by_name['TicketService'] = _TICKETSERVICE

# @@protoc_insertion_point(module_scope)
